# Generated by Django 4.1.1 on 2022-11-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_item_delete_post_delete_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_img",
            field=models.ImageField(blank=True, null=True, upload_to="imange/"),
        ),
        migrations.AlterField(
            model_name="item",
            name="item_price",
            field=models.IntegerField(max_length=20),
        ),
    ]
