# Generated by Django 4.1.3 on 2022-11-25 05:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_item_item_date_alter_item_item_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='item_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
