# Generated by Django 4.1.1 on 2022-11-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_upload_file",
                    models.FileField(upload_to="user_upload_files/ %Y%m%d/"),
                ),
            ],
        ),
    ]
